server:
  port: ${port:8502}

eureka:
  client:
    serviceUrl:
      defaultZone: ${eureka.serviceUrl:http://127.0.0.1:8501/eureka/}

spring:
  application:
    name: cloud-config
  cloud:
    config:
      label: master
      server:
        git:
          uri: ${git.uri:http://admin@localhost:8078/r/config-server.git}
          username: ${git.username:admin}
          password: ${git.password:admin}
          search-paths: ${git.paths:*}